### ISSUE TITLE
Dataset View Selected Tab Should Come From Query Param

### ISSUE THREAD

**Issue by NathanielScottStevens** [Datastillery/react_discovery_ui#62]
The selected tab from dataset detail should be set from a query param so that a user can directly navigate to any tab on the dataset details page.

AC:
[ ] User can navigate directly to any tab of the details page via the url
[ ] Bookmarks work
[ ] Back button returns the user to previous tab

**Tech Notes**
* The logic for this is in place but selecting a tab does not update the url which means it is only useful if a user types the query param into the url manually.
* Try and make this a path variable rather than a query parameter

**Comment by LtChae** [comment]
Was this a requirement that we missed at some point? This is a good idea for user experience (if not developer sanity) but I don't recall it being discussed.

**Comment by NathanielScottStevens** [comment]
I have no idea. There is logic in place for this to happen so I'm not sure if it was just never tested or if it worked previously and somehow regressed.

**Comment by abrock-accenture** [comment]
This may be an implementation detail, but I think I would prefer a path-based variable rather than a query param.

`https://discovery.smartcolumbusos.com/dataset/:organizationName/:datasetName/details`
`https://discovery.smartcolumbusos.com/dataset/:organizationName/:datasetName/chart`
`https://discovery.smartcolumbusos.com/dataset/:organizationName/:datasetName/query`

**Comment by LtChae** [comment]
I'd agree with calling it a feature and that we should make it a path variable if that's feasible.

**Comment by ManApart** [comment]
I agree with Tim's agreement.
